### ISSUE TITLE
Compiled copy command does not include credentials

### ISSUE THREAD

**Issue by warrenronsiek** [sqlalchemy-redshift/sqlalchemy-redshift#155]
When I compile/print a copy command, the result does not contain the appropriate parameters. E.g.:
```
import sqlalchemy as sa
from sqlalchemy import Table, Column, MetaData
from sqlalchemy_redshift.dialect import VARCHAR
from sqlalchemy_redshift.commands import CopyCommand
engine = sa.create_engine('redshift+psycopg2://example')
metadata = MetaData()
users = Table('users', metadata,Column('id', Integer), Column('val', VARCHAR(20))
print(CopyCommand(users, data_location="s3://testing/test.csv", access_key_id='12345678901234567890', secret_access_key='1234567890123456789012345678901234567890').compile(engine))
```
returns:
```
COPY users FROM %(data_location)s
        WITH CREDENTIALS AS %(credentials)s
```
expected:
```
COPY users FROM 's3://testing/test.csv'
aws_access_key_id='12345678901234567890'
aws_secret_access_key='1234567890123456789012345678901234567890';
```

**Comment by dargueta** [comment]
This is actually a security feature inside SQLAlchemy, not a bug. For more detailed information, see [here](https://docs.sqlalchemy.org/en/latest/faq/sqlexpressions.html#how-do-i-render-sql-expressions-as-strings-possibly-with-bound-parameters-inlined).

Anyway, short answer is you need to pass `compile_kwargs={'literal_binds': True}` in the call to `compile()`. This isn't an issue when you hand the dialect the command because it'll do it internally, but if you want to render the query with them you'll need to do something like:

```py
CopyCommand().compile(engine, compile_kwargs={'literal_binds': True})
```
